# Generated by Django 3.2.13 on 2022-05-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.TextField(blank=True, help_text='Use commas to separate tags', null=True),
        ),
    ]
