# Generated by Django 3.2.13 on 2022-05-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='make_public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
